import { db } from "./db";
import { projects, teams, DEFAULT_TEAMS } from "@shared/schema";

const seedProjects = [
  {
    title: "Cobli Mass Updater",
    status: "beta_privado",
    type: "automacao",
    tags: [] as string[],
    team: "CS",
    owner: "Ulisses de Almeida Gonçalves",
    summary: "Desafogar o time de DSE com importações de dados em massa e garantir um SLA mais estreito atualizações. Garantir melhoria do indicador de Config no basic value.",
    problem: "- Desafogar o time de DSE com importações de dados em massa e garantir um SLA mais estreito atualizações\n- Garantir melhoria do indicador de Config no basic value",
    solution: "https://ai.studio/apps/drive/1E_D-suSg8VTsHEkfRnbMh6kma9f00B1A",
    dataDependencies: "",
    risks: "Preciso de auxílio para verificar questões de segurança devido ao uso de chave de API",
    metrics: "",
    links: {},
  },
  {
    title: "Assistente Painel",
    status: "beta_privado",
    type: "automacao",
    tags: [] as string[],
    team: "Tech",
    owner: "Raphael Cunha Andresa Sombra",
    summary: "Nova experiência de assistente de frota no painel para clientes logados.",
    problem: "Nova experiência de assistente de frota no painel para clientes logados.",
    solution: "https://painel.cobli.co/ai\nAssistente (chat) com respostas sobre dados da frota:\n- segurança e vídeos recomendados\n- manutenção\n- análise de status de sinal\n- análises de cadastro\n- artigos de suporte\n- dados de produtividade\n- geração de gráficos e relatórios.",
    dataDependencies: "",
    risks: "Precisamos definir questões de Knowleage Base de dados. Quais dados são publicos, de cliente ou coblers. Além disso criar padrões a nivel ORG para esses dados. Assim todos alimentam as mesmas bases gerando mesmas respostas!",
    metrics: "",
    links: {},
  },
  {
    title: "Coblini Agente Qualificação",
    status: "beta_privado",
    type: "automacao",
    tags: [] as string[],
    team: "Marketing",
    owner: "Tiago Valle",
    summary: "Fazer o atendimento inicial, qualificação e engajamento de leads para vendas, conduzindo a conversa com potenciais clientes até o agendamento da demonstração com vendedor.",
    problem: "Fazer o atendimento inicial, qualificação e engajamento de leads para vendas, conduzindo a conversa com potenciais clientes até o agendamento da demonstração com vendedor. Inicialmente esperamos potencializar o desempenho de SDRs e, em paralelo, desenvolver um novo ponto de contato com leads que ofereça menos atritos que o atual.",
    solution: "- construção de agente integrado com whatsapp (conector não oficial)\n- interface web para gestão de agente e leads\n- integração com serviços diversos\n- uso controlado com aproximadamente 100 novas conversas por semana",
    dataDependencies: "",
    risks: "O gargalo atual é na integração com API oficial da Meta. Tivemos uma suspensão temporária do numero pela envio de mensagens ativas.\nOutra medida para esse momento é um acompanhamento geral sobre segurança e alocação dos serviços na infra da Cobli",
    metrics: "",
    links: {},
  },
  {
    title: "Pocket Demo",
    status: "beta_privado",
    type: "automacao",
    tags: [] as string[],
    team: "Marketing",
    owner: "Ivy",
    summary: "Criar ferramenta que apresente nosso sistema de forma objetiva, exibindo telas, funcionalidades e comentários sobre elas.",
    problem: "Criar ferramenta que apresente nosso sistema de forma objetiva, exibindo telas, funcionalidades e comentários sobre elas. Inicialmente deve ser usada por Pré-vendas e Vendas para engajar leads em seus próximos passos e tomadas de decisão",
    solution: "- painel para criação, edição e repositório de Tours no painel\n- versões de tours no painel para diferentes fins e times\n- piloto",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Agendamento automático de Entrevista",
    status: "beta_privado",
    type: "automacao",
    tags: [] as string[],
    team: "People",
    owner: "Leonardo Arruda",
    summary: "Acesso as agendas dos entrevistadores para facilitar o agendamento de entrevistas",
    problem: "Acesso as agendas dos entrevistadores para facilitar o agendamento de entrevistas",
    solution: "automação criada em uma vaga (atendimento ao cliente). Vamos configurar em novas vagas.",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "CS Enablement - Powered by AI",
    status: "beta_privado",
    type: "automacao",
    tags: [] as string[],
    team: "CS",
    owner: "Abrahao Elian, João Gabriel Guariento",
    summary: "Construção célula enablement em CS a partir de iniciativas de AI. Gerando redução de custos e elevando qualidade e padronização do time.",
    problem: "Prioridade do time de CS como projeto estruturante.\nObjetivo: construção célula enablement em CS a partir de iniciativas de AI. Gerando redução de custos (não contratação de 2 a 3 HC para montar a área) e elevando qualidade e padronização do time.\nEntrega inicial: Kick Off de novos clientes. A IA avalia a reuniões de onboarding de acordo com um manual de boas práticas, atribui notas e gera um relatório final para avaliar a estratégia de implantação",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Support AI",
    status: "em_desenvolvimento",
    type: "automacao",
    tags: [] as string[],
    team: "DSI",
    owner: "Miqueias Nascimento Pereira",
    summary: "Assistente de IA para suporte técnico interno.",
    problem: "Assistente de IA para suporte técnico interno.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Contract Updater",
    status: "em_desenvolvimento",
    type: "automacao",
    tags: [] as string[],
    team: "DSI",
    owner: "Fernando Freitas Alves",
    summary: "Automação para atualização de contratos.",
    problem: "Automação para atualização de contratos.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Free Tools App",
    status: "em_desenvolvimento",
    type: "automacao",
    tags: [] as string[],
    team: "Marketing",
    owner: "Tiago Valle",
    summary: "Aplicativo de ferramentas gratuitas para marketing.",
    problem: "Aplicativo de ferramentas gratuitas para marketing.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Otimizar a criação e atualização do PDI por meio da integração de dados de performance",
    status: "em_desenvolvimento",
    type: "automacao",
    tags: [] as string[],
    team: "People",
    owner: "Isabella Marinho",
    summary: "Otimizar a criação e atualização do PDI por meio da integração de dados de performance.",
    problem: "Otimizar a criação e atualização do PDI por meio da integração de dados de performance",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Conferência de folha de pagamento",
    status: "em_desenvolvimento",
    type: "automacao",
    tags: [] as string[],
    team: "People",
    owner: "Samantha Silveira",
    summary: "Automação para conferência de folha de pagamento.",
    problem: "Automação para conferência de folha de pagamento.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Otimização de treinamentos de Onboarding",
    status: "em_desenvolvimento",
    type: "automacao",
    tags: [] as string[],
    team: "People",
    owner: "Isabella Marinho",
    summary: "Otimização de treinamentos de onboarding usando IA.",
    problem: "Otimização de treinamentos de onboarding usando IA.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Apresentação interativa Cobli Cam",
    status: "em_desenvolvimento",
    type: "automacao",
    tags: [] as string[],
    team: "Marketing",
    owner: "Ivy",
    summary: "Apresentação interativa do produto Cobli Cam.",
    problem: "Apresentação interativa do produto Cobli Cam.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Field Support AI",
    status: "ideia",
    type: "automacao",
    tags: [] as string[],
    team: "DSI",
    owner: "Miqueias Nascimento Pereira",
    summary: "IA para suporte em campo.",
    problem: "IA para suporte em campo.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "CRM Watchtower",
    status: "ideia",
    type: "automacao",
    tags: [] as string[],
    team: "DSI",
    owner: "Fernando Freitas Alves",
    summary: "Monitoramento inteligente do CRM.",
    problem: "Monitoramento inteligente do CRM.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Content AI Workforce",
    status: "ideia",
    type: "automacao",
    tags: [] as string[],
    team: "Marketing",
    owner: "Tiago Valle",
    summary: "Força de trabalho de IA para criação de conteúdo.",
    problem: "Força de trabalho de IA para criação de conteúdo.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Pulse Enterprise",
    status: "piloto",
    type: "automacao",
    tags: [] as string[],
    team: "CS",
    owner: "Abrahao Elian",
    summary: "Ferramenta Pulse para clientes enterprise.",
    problem: "Ferramenta Pulse para clientes enterprise.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "AI API",
    status: "piloto",
    type: "automacao",
    tags: [] as string[],
    team: "Tech",
    owner: "Raphael Cunha",
    summary: "API centralizada de IA.",
    problem: "API centralizada de IA.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "DSI Assistant",
    status: "producao",
    type: "automacao",
    tags: [] as string[],
    team: "DSI",
    owner: "Yuri Frensel Lobo Zelada",
    summary: "Assistente de IA para o time DSI em produção.",
    problem: "Assistente de IA para o time DSI em produção.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "QBR Inteligente",
    status: "producao",
    type: "automacao",
    tags: [] as string[],
    team: "CS",
    owner: "Abrahao Elian",
    summary: "QBR (Quarterly Business Review) inteligente automatizado.",
    problem: "QBR (Quarterly Business Review) inteligente automatizado.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Gerador de Kick-off",
    status: "producao",
    type: "automacao",
    tags: [] as string[],
    team: "CS",
    owner: "Abrahao Elian, João Gabriel Guariento",
    summary: "Gerador automático de materiais para kick-off de clientes.",
    problem: "Gerador automático de materiais para kick-off de clientes.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Auditor de obstrução",
    status: "producao",
    type: "automacao",
    tags: [] as string[],
    team: "Vendas",
    owner: "Fabio Araujo Petersen",
    summary: "Auditor automático de obstrução de câmeras.",
    problem: "Auditor automático de obstrução de câmeras.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Onboarding APP",
    status: "em_desenvolvimento",
    type: "automacao",
    tags: [] as string[],
    team: "Vendas",
    owner: "Fabio Araujo Petersen",
    summary: "App de onboarding para vendas.",
    problem: "App de onboarding para vendas.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Gerador de pílula",
    status: "ideia",
    type: "automacao",
    tags: [] as string[],
    team: "Vendas",
    owner: "Fabio Araujo Petersen",
    summary: "Criar um fluxo que busque vídeos ou dados extremos de clientes em piloto e envie para o AE já com a sugestão de texto para manter a cadência de FUP's.",
    problem: "Criar um fluxo que busque vídeos ou dados extremos de clientes em piloto e envie para o AE já com a sugestão de texto para ele enviar no whatsapp do cliente e manter a cadência de FUP's.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Meetrox enlightment",
    status: "em_desenvolvimento",
    type: "automacao",
    tags: [] as string[],
    team: "Vendas",
    owner: "Fabio Araujo Petersen",
    summary: "Comparar massivamente os dados do Meetrox (top performers vs resto) para gerar insights sobre reuniões dos top performers.",
    problem: "Comparar massivamente os dados do Meetrox (top performers vs resto) para gerar insights sobre reuniões dos top performers",
    solution: "",
    dataDependencies: "",
    risks: "API da meetROX para baixar as trascrições de reuniões.",
    metrics: "",
    links: {},
  },
  {
    title: "Agente pré demo",
    status: "ideia",
    type: "automacao",
    tags: [] as string[],
    team: "Vendas",
    owner: "Fabio Araujo Petersen",
    summary: "Agente que utiliza os dados levantados pelo SDR, puxa o site da empresa, pesquisa o setor e pesquisa o linkedin para enviar uma qualificação ao AE antes da demo.",
    problem: "Agente que utiliza os dados levantados pelo SDR, puxa o site da empresa, pesquisa o setor e pesquisa o linkedin para enviar uma qualificação ao AE antes da demo.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "Auditor de hardware",
    status: "beta_privado",
    type: "automacao",
    tags: [] as string[],
    team: "Vendas",
    owner: "Fabio Araujo Petersen",
    summary: "Fluxo automatizado para extrair o funcionamento dos dispositivos em piloto e informar o AE, com ações sugeridas.",
    problem: "Fluxo automatizado para extrair o funcionamento dos dispositivos em piloto e informar o AE, com ações sugeridas. Acompanhar os status do ticket e abrir novos ticket",
    solution: "Fluxo já é capaz de puxar os fleetID's dos clientes em piloto ativo e buscar no databricks o status de cada um dos tickets. Já integramos o slack no fluxo e estamos enviando diariamente o resumo geral e por executivo.",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
  {
    title: "SofIA - Digital Scale CS",
    status: "em_desenvolvimento",
    type: "automacao",
    tags: [] as string[],
    team: "CS",
    owner: "Abrahao Elian Victor Cezar Leandro da Silva Martins Ulisses de Almeida Gonçalves",
    summary: "Implementar um ecossistema de agentes de IA (SofIA) para potencializar a estratégia de Digital Scaled CS.",
    problem: "Prioridade do time de CS como projeto estruturante.\nObjetivo: Implementar um ecossistema de agentes de IA (SofIA) para potencializar a estratégia de Digital Scaled CS. A iniciativa visa transformar o atendimento reativo em uma operação de inteligência preditiva. O foco inicial da SofIA será a intervenção em clientes com inatividade severa.",
    solution: "",
    dataDependencies: "",
    risks: "",
    metrics: "",
    links: {},
  },
];

const allTeams = ["Tech", "Supply", "Marketing", "CS", "DSI", "People", "Vendas"];

export async function seedDatabase() {
  const existingTeams = await db.select({ id: teams.id }).from(teams).limit(1);
  if (existingTeams.length === 0) {
    console.log("Seeding default teams...");
    for (const name of allTeams) {
      await db.insert(teams).values({ name }).onConflictDoNothing();
    }
    console.log(`Seeded ${allTeams.length} teams.`);
  }

  const existingProjects = await db.select({ id: projects.id }).from(projects).limit(1);
  if (existingProjects.length === 0) {
    console.log("Seeding projects from spreadsheet...");
    for (const project of seedProjects) {
      await db.insert(projects).values(project);
    }
    console.log(`Seeded ${seedProjects.length} projects.`);
  }
}
